---
- name: Setup community repo for proxmox
  hosts: all
  gather_facts: yes
  gather_subset: min
  become: true
  become_user: root
  tasks:
    - name: Add community repo
      apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        state: present
        update_cache: no
        filename: pve-no-subscription
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Remove enterprise repo
      ansible.builtin.file:
        state: absent
        path: '{{ item }}'
      loop:
        - /etc/apt/sources.list.d/pve-enterprise.list
        - /etc/apt/sources.list.d/ceph.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

